name: 'Label new Pull Requests by FireWork Production Private Ltd.'
description: 'Add a label when PR is opened'
author: 'up1512001'

inputs:
  gh-token:
    description: 'The Github token for authentication'
    required: true
  label:
    description: 'The label to be applied to pull request'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'blue'