name: "Hello"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  hello:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: black1512/Github-WorkFlow-Playing-2@main
      with:
        label: "needs-review"
        gh-token: ${{ secrets.GITHUB_TOKEN }}
      
            
