name: "Hello"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  hello:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          gh-token: ${{secrets.PERSONAL_WORKFLOW_TOKEN}}
          label: 'needs-review'